export const dockApps = [
  { id: "finder", name: "Portfolio", icon: "finder.webp", canOpen: true },
  { id: "launchpad", name: "Launchpad", icon: "Launchpad.webp", canOpen: true },
  { id: "safari", name: "Safari", icon: "safari.webp", canOpen: true },
  { id: "photos", name: "Gallery", icon: "photos.webp", canOpen: true },
  { id: "contact", name: "Contact", icon: "contact.webp", canOpen: true },
  { id: "terminal", name: "Terminal", icon: "terminal.webp", canOpen: true },
  { id: "settings", name: "System Settings", icon: "settings.webp", canOpen: true },
  { id: "calculator", name: "Calculator", icon: "calculator.webp", canOpen: true },
  { id: "notes", name: "Notes", icon: "notes.webp", canOpen: true },
  { id: "call", name: "FaceTime", icon: "call.webp", canOpen: true },
  { id: "messages", name: "Messages", icon: "message.webp", canOpen: true },
  { id: "appletv", name: "Apple TV", icon: "appletv.webp", canOpen: true },
  { id: "appstore", name: "App Store", icon: "appstore.webp", canOpen: true },
  { id: "calendar", name: "Calendar", icon: "calendar.png", canOpen: true },
  { id: "weather", name: "Weather", icon: "weather.webp", canOpen: true },
  { id: "vscode", name: "VS Code", icon: "vscode.webp", canOpen: true },
  { id: "postman", name: "Postman", icon: "postman.webp", canOpen: true },
  { id: "map", name: "Maps", icon: "map.webp", canOpen: true },
  { id: "font", name: "Font Book", icon: "font.webp", canOpen: true },
  { id: "telegram", name: "Telegram", icon: "telegram.webp", canOpen: true },
  { id: "music", name: "Music", icon: "music.webp", canOpen: true },
  { id: "folder", name: "Projects Folder", icon: "folder.webp", canOpen: true },
  { id: "trash", name: "Trash", icon: "trash.webp", canOpen: true },
];
