import {
  PROJECT_1_URL,
  PROJECT_1_GITHUB,
  PROJECT_2_URL,
  PROJECT_2_GITHUB,
  PROJECT_3_URL,
  PROJECT_3_GITHUB,
  PROJECT_4_URL,
  PROJECT_4_GITHUB,
} from "./env";

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "NewTube",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-5",
      windowPosition: "top-[5vh] left-5",
      children: [
        {
          id: 1,
          name: "NewTube Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This platform is a modern video streaming application built for performance, scalability, and user engagement. It features an advanced video player with quality controls, playback speed, picture-in-picture, and keyboard shortcuts for a smooth experience. Powered by Mux, videos are processed, optimized, and delivered globally via a fast CDN.",
            "It includes AI-powered tools for thumbnail generation, title suggestions, and description optimization, helping creators boost discoverability. The Creator Studio provides analytics, engagement metrics, and growth tracking. ",
            "Built with Next.js, Tailwind CSS, tRPC, and PostgreSQL, it ensures a fast, responsive, and scalable architecture across all devices.",
          ],
        },
        {
          id: 2,
          name: "newtube.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_1_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "newtube.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/newtube.webp",
          imageMobUrl: "/projects/mobile/newtube-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_1_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 6,
      name: "Snsta",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 right-80",
      windowPosition: "top-[20vh] left-7",
      children: [
        {
          id: 1,
          name: "Snsta Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 right-10",
          description: [
            "Download photos, videos, and reels from Instagram easily with a fast, user-friendly web app.",
            "Simply paste the link and get high-quality content instantly without any login or hassle. ",
            "Designed for speed, reliability, and convenience, this tool lets you save your favorite Instagram media anytime, anywhere, in just a few quick clicks.",
          ],
        },
        {
          id: 2,
          name: "snsta.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_2_URL,
          position: "top-20 left-20",
        },
        {
          id: 4,
          name: "snsta.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 left-80",
          imageUrl: "/projects/snsta.webp",
          imageMobUrl: "/projects/mobile/snsta-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_2_GITHUB,
          position: "top-60 left-5",
        },
      ],
    },
    {
      id: 7,
      name: "Resume Ats Scanner",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-10 left-80",
      windowPosition: "top-[33vh] left-7",
      children: [
        {
          id: 1,
          name: "Resume Ats Scanner Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This is an AI-powered resume parsing and analysis platform designed to help job seekers optimize their resumes for Applicant Tracking Systems (ATS).",
            "It extracts key information from uploaded resumes, analyzes them against job descriptions, and provides detailed feedback on keyword optimization, formatting issues, and content improvements.",
            "Built with Groq API, it ensures accurate parsing and intelligent scoring, helping users increase their chances of passing through automated screening processes.",
          ],
        },
        {
          id: 2,
          name: "resumeatsscanner.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_3_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "resumeatsscanner.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/resume-ats.webp",
          imageMobUrl: "/projects/mobile/resume-ats-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_3_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
    {
      id: 8,
      name: "Docs Editor",
      icon: "/images/folder.webp",
      kind: "folder",
      position: "top-52 left-5",
      windowPosition: "top-[46vh] left-7",
      children: [
        {
          id: 1,
          name: "Docs Editor Project.txt",
          icon: "/images/txt.webp",
          kind: "file",
          fileType: "txt",
          position: "top-5 left-10",
          description: [
            "This is a powerful, real-time collaborative document editor built to allow multiple users to edit rich-text documents simultaneously with high performance.",
            "Powered by Liveblocks and Yjs CRDT, it features conflict-free editing, live cursor tracking, presence indicators, and inline comment threads. It integrates Tiptap for rich-text formatting, document headers, and image insertion.",
            "Built with Next.js 15, Clerk for secure user authentication, Convex for database storage, and Zustand for state management, ensuring a modern, responsive, and secure experience.",
          ],
        },
        {
          id: 2,
          name: "docs-editor.com",
          icon: "/images/safari.webp",
          kind: "file",
          fileType: "url",
          href: PROJECT_4_URL,
          position: "top-10 right-20",
        },
        {
          id: 4,
          name: "docs-editor.png",
          icon: "/images/image.webp",
          kind: "file",
          fileType: "img",
          position: "top-52 right-80",
          imageUrl: "/projects/docs-editor.webp",
          imageMobUrl: "/projects/mobile/docs-editor-mob.webp",
        },
        {
          id: 5,
          name: "github.com",
          icon: "/images/github.webp",
          kind: "file",
          fileType: "fig",
          href: PROJECT_4_GITHUB,
          position: "top-60 right-20",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 4,
      name: "about-me.txt",
      icon: "/images/txt.webp",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      description: [
        "Hey! I'm Nishant Agarwal, a backend and blockchain engineer at Bennett University.",
        "I ship production systems: ZK identity (Krydo), on-chain assessment (BlockForge / NetCrypt 2026), and OSS merged into Hardhat, Hyperlane, FilOzone, and Mastra.",
        "Former Web3 intern at Digital South Trust. Finalist at LNMHacks 8.0. Top 20 at Kshitij 2026, IIT Kharagpur.",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.webp",
      kind: "file",
      fileType: "pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/trash-1.webp",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/images/image.webp",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/images/trash-2.webp",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};
